type User {
  id: ID
  name: String
  email: String
  phoneNumber: String
  profile: Profile
}
input UserInput {
  name: String 
  email: String
  phoneNumber: String
}
input DeleteUserInput {
  id: Int
  email: String
}

type Query {
  user(id: Int): User
  users: [User]
}
type Mutation {
  createUser(data: UserInput): User!
  updateUser(id: Int!, data: UserInput): User!
  deleteUser(data: DeleteUserInput!): Boolean
}