type Contact {
    id: Int
    name: String
    email: String
    phoneNumber: String
}
input ContactInput {
    name: String
    email: String
    phoneNumber: String
}

type Query {
    contacts: [Contact]!
}
type Mutation {
    createContact(data: ContactInput): Contact
    updateContact(id: Int!, data: ContactInput): Contact
    deleteContact(id: Int): Boolean
}